vllm_service:
    model_impl: 
        path: implement.model.qwen_vl_vllm
        params:
            model_name_or_path: /aiarena/project/2014-p15/models/Qwen2VL-2B-Instruct
            gpu_memory_utilization: 0.85
            enable_prefix_caching: false
            max_model_len: 8192
            enforce_eager: false
            mm_processor_kwargs:
                min_pixels: 3136
                max_pixels: 401408
            limit_mm_per_prompt:
                image: 5
                video: 0
    gpu_id: -1
    server_port: 40000
    nccl_port: 41000
    host: 0.0.0.0
tf_service:
    model_impl: 
        path: implement.model.qwen_vl_tf
        params:
            model_name_or_path: /aiarena/project/2014-p15/models/Qwen2VL-2B-Instruct
            min_pixels: 3136
            max_pixels: 401408
    token_budget: 20000
    host: 0.0.0.0
    port: 42000
data_service:
    dataset_impl: 
        path: implement.dataset.science_qa
        params:
            dataset_path: /aiarena/project/2014-p15/datasets/ScienceQA
            system_prompt_path: data_service/prompt/science_qa.txt
    processor_impl:
        path: implement.model.qwen_vl_tf
        params:
            model_name_or_path: /aiarena/project/2014-p15/models/Qwen2VL-2B-Instruct
            min_pixels: 3136
            max_pixels: 401408
    reward_impl:
        accuracy: 
            path: data_service.rewards.multiple_choice
        format: 
            path: data_service.rewards.format
    global_batch_size: 16
    per_prompt_generation_count: 8
    max_response_length: 500
    max_prompt_length: 500
    max_micro_step_num: 2
    gpu_num: 7
    token_budget: 7000
    temperature: 0.7
    vllm_host: localhost
    vllm_server_port: 40000
    vllm_nccl_port: 41000
    tf_host: "10.244.175.218"
    tf_port: 42000
main:
    model_impl:
        path: implement.model.qwen_vl_tf
        params:
            model_name_or_path: /aiarena/project/2014-p15/models/Qwen2VL-2B-Instruct
            min_pixels: 3136
            max_pixels: 401408
    run_name: "science_qa"
    model_path: "/aiarena/project/2014-p15/models/Qwen2VL-2B-Instruct"
    save_dir: "/aiarena/project/2014-p15/models/Qwen2VL-2B-GRPO-science_qa"
    grpo_beta: 0.04
    lr: 1.0e-6
    total_steps: 1000
    save_steps: 100
    queue_depth: 2
    max_grad_norm: 1.0
    max_length: 1024
    epsilon_low: 0.2
    epsilon_high: 0.28