vllm_service:
    model_impl: 
        path: implement.model.qwen_vllm
        params:
            model_name_or_path: /aiarena/project/2014-p15/models/Qwen2.5-3B-Instruct
            gpu_memory_utilization: 0.85
            enable_prefix_caching: false
            max_model_len: 8192
            enforce_eager: false
    gpu_id: -1
    server_port: 40000
    nccl_port: 41000
    host: 0.0.0.0
tf_service:
    model_impl: 
        path: implement.model.qwen_tf
        params:
            model_name_or_path: /aiarena/project/2014-p15/models/Qwen2.5-3B-Instruct
    token_budget: 20000
    host: 0.0.0.0
    port: 42000
data_service:
    dataset_impl: 
        path: implement.dataset.gsm8k
        params:
            dataset_path: /aiarena/project/2014-p15/datasets/gsm8k_train.jsonl
            system_prompt_path: /aiarena/project/2014-p15/MyGO_v1/data_service/prompt/math_r1v.txt
    processor_impl:
        path: implement.model.qwen_tf
        params:
            model_name_or_path: /aiarena/project/2014-p15/models/Qwen2.5-3B-Instruct
    reward_impl:
        accuracy: 
            path: data_service.rewards.accuracy_r1v
        format: 
            path: data_service.rewards.format
    global_batch_size: 16
    per_prompt_generation_count: 8
    max_response_length: 500
    max_prompt_length: 500
    max_micro_step_num: 2
    gpu_num: 7
    token_budget: 7000
    temperature: 0.7
    vllm_host: localhost
    vllm_server_port: 40000
    vllm_nccl_port: 41000
    tf_host: "10.244.175.218"
    tf_port: 42000
main:
    model_impl:
        path: implement.model.qwen_tf
        params:
            model_name_or_path: /aiarena/project/2014-p15/models/Qwen2.5-3B-Instruct
    run_name: "test_pure_text"
    model_path: /aiarena/project/2014-p15/models/Qwen2.5-3B-Instruct
    save_dir: /aiarena/project/2014-p15/models/Qwen2.5-GRPO-test
    grpo_beta: 0.04
    lr: 1.0e-6
    total_steps: 1000
    save_steps: 100
    queue_depth: 1
    max_grad_norm: 1.0
    max_length: 1024
    epsilon_low: 0.2
    epsilon_high: 0.28